TYPE_PATH = "video"
OUTPUT = "/home/vu/Desktop/work/output"
EXP = "ByteTrack/exps/example/mot/yolox_x_mix_mot20_ch.py"
CHECKPOINT = "pretrained/bytetrack_x_mot20.tar"
CHECKPOINT_AGEGENDER = "pretrained/model_imdb_cross_person_4.22_99.46.pth.tar"
WEIGHT = "pretrained/yolov8x_person_face.pt"
IMAGE_EXT = [".jpg", ".jpeg", ".webp", ".bmp", ".png"]


PATH = "input/hackathon/Doto_103.mp4"
# PATH = "input/hackathon/Doto_116.mp4"
# PATH = "input/hackathon/Doto_132.mp4"
# PATH = "input/hackathon/Doto_134.mp4"
# PATH = "input/hackathon/Kabu_1.mp4"
# PATH = "input/hackathon/Kabu_8.mp4"
# PATH = "input/hackathon/Kabu_9.mp4"
# PATH = "input/hackathon/Kabu_12.mp4"
# PATH = "input/hackathon/Kabu_75.mp4"
# PATH = "input/hackathon/Kabu_83.mp4"
# PATH = "input/hackathon/Kabu_88.mp4"
